/* INTERMEDIATE LEVEL - FILTERING DATA (OPERATORS) */

/* TO FILTERING THE DATA THERE ARE MANY TYPES OF OPERATORS */

UPDATE customers
SET score=0
WHERE id=5

--1) COMPARSION OPERATOR

--A) = OPERATOR     (RETRIEVE ALL THE CUSTOMERS FROM GERMANY)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE country='Germany'

--B) <> != OPERATOR     (RETRIEVE ALL THE CUSTOMERS WHO ARE NOT FROM GERMANY)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE country != 'Germany'

--C) > OPERATOR        (RETRIEVE ALL CUSTOMERS WITH A SCORE GREATER THAN 500)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE score>500

--D) >= OPERATOR      (RETRIEVE ALL CUSTOMERS WITH A SCORE GREATER THAN OR EQUAL TO 500)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE score>=500

--E) < OPERATOR      (RETRIEVE ALL CUSTOMERS WITH A SCORE LESS THAN 500)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE score<500

--F) <= OPERATOR    (RETRIEVE ALL THE CUSTOMERS WITH A SCORE LESS THAN OR EQUAL TO 500)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE score<=500


--2) LOGICAL OPERATORS

--A) AND OPERATOR   (RETERIEVE ALL THE CUSTOMERS WHO ARE FROM 'USA' AND HAVE A SCORE GREATER THAN 500)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE score>500 AND
country='USA'

--B) OR OPERATOR   (RETERIEVE ALL THE CUSTOMERS WHO ARE FROM 'USA' OR HAVE A SCORE GREATER THAN 500)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE score>500 OR
country='UK'

--C) NOT OPERATOR   (RETERIEVE ALL THE CUSTOMERS WITH A SCORE NOT LESS THAN 500)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE NOT score<500

--3) RANGE OPERATOR 

--A) BETWEEN OPERATOR    (RETERIEVE ALL THE CUSTOMERS WHOSE SCORE FALLS IN THE RANGE BETWEEN 100 AND 500)
SELECT*
FROM customers

SELECT*
FROM customers
WHERE score BETWEEN 100 AND 500

SELECT*
FROM customers
WHERE score>=100 AND score<=500

--4) MEMBERSHIP OPERATOR

--A) IN OPERATOR    (RETERIEVE ALL CUSTOMERS EITHER FROM ‘GERMANY’ OR ‘USA’)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE country IN ('Germany','USA')

SELECT*
FROM customers
WHERE country='Germany' OR country='USA'

--B) NOT IN OPERATOR    (RETERIEVE ALL CUSTOMERS EITHER  NOT FROM ‘GERMANY’ OR ‘USA’)

SELECT*
FROM customers


SELECT*
FROM customers
WHERE country NOT IN ('Germany','USA')


--5) SEARCH OPERATOR  

--A) SEARCH START LETTER 'M'    (FIND ALL CUSTOMERS WHOSE first_name IS START WITH ‘M’)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE first_name LIKE 'M%'

--B) SEARCH END LETER 'N'   (FIND ALL CUSTOMERS WHOSE first_name IS ENDS WITH ‘N’)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE first_name LIKE '%N'

--C) SEARCH CONTAINS 'R' (FIND ALL CUSTOMERS WHOSE first_name CONTAINS ‘R’)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE first_name LIKE '%R%'

--D)SEARCH CONTAINS 'R' (FIND ALL CUSTOMERS WHOSE first_name HAS ‘R’ IN THE THIRD POSITION)

SELECT*
FROM customers

SELECT*
FROM customers
WHERE first_name LIKE '__R%'